# -*- coding: utf-8 -*-
VI = {
'AmNhom':'Ấm nhôm','AnhCuoi_Tex':'Ảnh cưới bố mẹ (khung treo)','AnhGiaDinh_Tex':'Ảnh gia đình 1997 (khung treo)','AntenTV_MaiNha':'Ăng-ten TV chữ Y trên mái',
'AoMuaBo_TreoCua':'Áo mưa của bố treo cửa','AoTangGap':'Áo tang gấp (trên sạp)','AoTang_Phoi_01':'Áo tang phơi #1','AoTang_Phoi_02':'Áo tang phơi #2','AoTang_Phoi_03':'Áo tang phơi #3','AoTang_Phoi_04':'Áo tang phơi #4','AoTang_Phoi_05':'Áo tang phơi #5',
'BaloKhoi_XanhLa':'Ba lô của Khôi (xanh lá)','BanAn_Bo':'Bộ bàn ăn + ghế','BanCanhGiuong_Thuoc':'Bàn cạnh giường (thuốc)','BanChaiCo_XaPhong':'Bàn chải cọ + xà phòng','BanCoHoc_Go':'Bàn gỗ (đồ học cũ)',
'BanGiay_Go':'Bàn giấy gỗ','BanHoc_Khoi_Bo':'Bộ bàn học của Khôi','BanHoc_Nhim':'Bàn học của Nhím','BanThoGiaTien_Set':'Bàn thờ gia tiên (cả bộ)','BanThoHam':'Bàn thờ hầm','BanThoThanTai':'Bàn thờ Thần Tài',
'BanThoVong_Dem1':'Bàn thờ vong — Đêm 1','BanThoVong_Dem2':'Bàn thờ vong — Đêm 2','BanThoVong_Dem3':'Bàn thờ vong — Đêm 3','BanTinh_Go':'Bàn tính gỗ','BanTrangDiem_Bo':'Bộ bàn trang điểm (+ gương)',
'BangCassette_Hop':'Hộp băng cassette','BangDienChinh':'Bảng điện chính (cầu dao, cầu chì)','BangGDVH_Tex':'Bằng "Gia đình văn hoá"','BangGia':'Bảng giá viết tay','BangTayGay':'Băng bột tay gãy (Nhím)',
'BaoBotGiat_XaPhong':'Bao bột giặt, xà phòng','BaoCu_TrenBan':'Báo cũ trên bàn','BaoTaiRong':'Bao tải rỗng','BaoXiMang_Chong':'Chồng bao xi măng','BaoXiMang_Chong2':'Chồng bao xi măng (2)','BaoXiMang_Le':'Bao xi măng lẻ',
'BatChao_An':'Bát cháo ăn','BatDia_DangUp_Ban':'Bát đĩa úp trên bàn','BatDia_TrongChau':'Bát đĩa trong chậu','BatNhang_FullAssembly':'Bát nhang (đủ bộ)','BauCuaSo_Granito_Bep':'Bậu cửa sổ granito — bếp',
'BauCuaSo_Granito_BoMe':'Bậu cửa sổ granito — bố mẹ','BauCuaSo_Granito_Khoi':'Bậu cửa sổ granito — Khôi','BeGiat':'Bể giặt xi măng','BeNuoc_Nap':'Bể nước có nắp','BeRua_Bo':'Bệ rửa xây + chậu inox + vòi',
'BepGas_Doi':'Bếp gas đôi','BienSoNha':'Biển số nhà tráng men','BinhGas':'Bình gas','BinhHoaLon_Gom':'Bình hoa gốm lớn','BinhHoaTho':'Bình hoa bàn thờ','BinhNongLanh':'Bình nóng lạnh',
'BinhNuocHocSinh':'Bình nước học sinh','BinhThuy_Phich':'Phích (bình thuỷ) nước','BoMia':'Bó mía','BoXoGauChau_WC':'Bộ xô – gáo – chậu WC','Bo_Chen_Tren_De':'Năm chén nước trên đế (bàn thờ hầm)',
'BonHoa_SanPhoi':'Bồn hoa xây sân phơi','BonNuocMai':'Bồn nước mái','BongCompact':'Bóng đèn compact','BongDa_Xep':'Quả bóng đá xẹp','BongDenSan_DayDien':'Bóng đèn chao tôn sân phơi + dây điện',
'BuiXiMang_San':'Bụi xi măng trên sàn','BupBe_NhuaCu':'Búp bê nhựa cũ','CanBanHang':'Cân bàn (bán hàng)','CanhBanCong_Phai':'Cánh cửa ban công (phải)','CanhBanCong_Trai':'Cánh cửa ban công (trái)',
'CanhCong_Phai (mở)':'Cánh cổng sắt phải (mở)','CanhCong_Trai (mở)':'Cánh cổng sắt trái (mở)','CapSach_TieuHoc':'Cặp sách tiểu học','CayChoi':'Cây chổi','CayChoiLongGa':'Chổi lông gà','ChaiNuocMam_Lo':'Chai nước mắm, lọ gia vị',
'ChanMenBong_GapGon':'Chăn mền bông gấp gọn','Chan_BatDiaTrongChan':'Bát đĩa trong chạn','ChauCayKieng_LaTo':'Chậu cây kiểng lá to','ChauCay_SanPhoi':'Chậu cây sân phơi','ChauLuoiHo':'Chậu lưỡi hổ',
'ChauNhua':'Chậu nhựa','ChauNhua_Up':'Chậu nhựa úp','ChauNuoc_KhanUot':'Chậu nước + khăn ướt (Nhím)','ChauTrauBa':'Chậu trầu bà','ChieuCoi_PhongTho':'Chiếu cói phòng thờ','ChieuMen_KhachO':'Chiếu + mền khách ngủ lại',
'ChoiCauBonCau':'Cọ bồn cầu','ChoiLau_Gop':'Chổi lau nhà + xô','ChoiQuet_Ky':'Chổi quét + ky hốt rác','ChongSoSach_Cu':'Chồng sổ sách cũ','ChongTre':'Chồng (bó) tre','ChuongDien_Chuong':'Chuông điện (chuông)',
'ChuongDien_Nut':'Chuông điện (nút bấm)','CocBanChai_NguoiLon':'Cốc bàn chải (người lớn)','CocBanChai_TreEm':'Cốc bàn chải (trẻ em)','ConDau_HopMuc':'Con dấu + hộp mực','CongSat_TruGach':'Trụ gạch cổng sắt',
'CotPhoi':'Cột phơi','CuaChinh_Phai (mở ra ngoài)':'Cửa chính — cánh phải (mở ra ngoài)','CuaChinh_Trai (mở ra ngoài)':'Cửa chính — cánh trái (mở ra ngoài)','CuaLamViec_Phai (mở)':'Cửa góc làm việc — cánh phải',
'CuaLamViec_Trai (mở)':'Cửa góc làm việc — cánh trái','CuaNgachCong (mở)':'Cửa ngách ở cổng','CuaPhongNhim_FullAssembly':'Cửa phòng Nhím (đủ bộ)','CuaSanPhoi':'Cửa ra sân phơi (hé 0,25 m)','CuaSatHam (mở)':'Cửa sắt hầm',
'CuaSatKinh (mở)':'Cửa sắt kính sau bếp','CuaSatXep_Dong':'Cửa sắt xếp mặt tiền tiệm','CuaSo_Bep_Phai':'Cửa sổ bếp (cánh phải)','CuaSo_Bep_Trai':'Cửa sổ bếp (cánh trái)','CuaSo_BoMe_Phai':'Cửa sổ phòng bố mẹ (phải)',
'CuaSo_BoMe_Trai':'Cửa sổ phòng bố mẹ (trái)','CuaSo_Khoi_Phai':'Cửa sổ phòng Khôi (phải)','CuaSo_Khoi_Trai':'Cửa sổ phòng Khôi (trái)','CuaWC_BoMe (mở)':'Cửa WC phòng bố mẹ','CuaWC_T1 (mở)':'Cửa WC tầng 1',
'CumAnhCu_TreoTuong':'Cụm ảnh cũ treo tường','CuonDayDien':'Cuộn dây điện','CuonDayDien_2':'Cuộn dây điện (2)','CuonLuoiThep':'Cuộn lưới thép','DayPhoi':'Dây phơi','Decal_BongVoi_A':'Decal bong vôi',
'Decal_ChuBatDien':'Chữ sơn đỏ "BẬT ĐIỆN"','DenBanHoc':'Đèn bàn học','DenChum_5Tay':'Đèn chùm 5 tay','DenCong_ChaoTon':'Đèn cổng chao tôn','DenHam_FullAssembly':'Đèn hầm — bóng dây tóc (đủ bộ)',
'DenHat_Ong':'Đèn hắt trần (ống)','DenNgu_BoMe':'Đèn ngủ đầu giường bố mẹ','DenNgu_Nhim':'Đèn ngủ của Nhím','DenOpTran':'Đèn ốp trần','DenTuyp_120':'Đèn tuýp máng 1,2 m','DenTuyp_60':'Đèn tuýp máng 0,6 m',
'DepToOng_Fix':'Dép tổ ong','Dep_Khach':'Dép khách','Dep_Nhim_Roi':'Dép của Nhím (rơi)','DiaKeoBanh_HatDua':'Đĩa kẹo bánh hạt dưa','DiaVCD_XepChong':'Đĩa VCD xếp chồng','DieuKhien':'Điều khiển bọc nilon',
'DoChoi_Lon':'Đồ chơi lớn (Nhím)','DoHoc_Nhim':'Đồ học trên bàn của Nhím','DoTuDauGiuong_Bo':'Đồ trên tủ đầu giường (bố)','DoTuDauGiuong_Me':'Đồ trên tủ đầu giường (mẹ)','DonTrangDiem':'Đôn ngồi trang điểm',
'DongHoDeBan_BaoThuc':'Đồng hồ báo thức để bàn','DongHoNuoc_HopCong':'Đồng hồ nước (dưới hộp công tơ)','DongHoQuaLac':'Đồng hồ quả lắc','DongHoTreo_Tiem':'Đồng hồ treo tường (tiệm)','DongHoTreo_Vuong':'Đồng hồ treo vuông',
'DongPhuc_Treo':'Đồng phục Nhím treo móc','GachMau_Chong':'Chồng gạch mẫu','GatTan_ThuyTinh':'Gạt tàn thuỷ tinh','GauBong_Cu':'Gấu bông cũ','GheAn_bo':'Ghế ăn (bố)','GheAn_khoi':'Ghế ăn (Khôi)','GheAn_me':'Ghế ăn (mẹ)',
'GheAn_nhim':'Ghế ăn (Nhím)','GheBanGiay':'Ghế bàn giấy','GheBanHoc_Go':'Ghế bàn học gỗ','GheDau_Go':'Ghế đẩu gỗ','GheDau_Nhua':'Ghế đẩu nhựa','GheNhua_Nhim':'Ghế nhựa của Nhím','GheTua_AoBo_Fix':'Ghế tựa + áo sơ mi của bố',
'GiaBatUp':'Giá bát úp','GiaDep_Bo':'Giá dép','GiaPhoiDo_Xep':'Giá phơi đồ xếp','GiaSach_Bo':'Giá sách (bộ)','GianPhoi_Gap':'Giàn phơi gấp','GiayBaoNhapHoc':'Giấy báo nhập học','GiayKeChan':'Giấy kê chân (hầm)',
'GiayKhen_Khoi':'Giấy khen của Khôi','GiayVeSinh_Treo':'Cuộn giấy vệ sinh treo','GiengTroi':'Giếng trời (mái lấy sáng)','GioQuanAo':'Giỏ quần áo','GiuongDoi_Bo':'Giường đôi (bộ)','GiuongDon_Khoi':'Giường đơn của Khôi',
'GiuongNhim_ChieuChan':'Giường Nhím + chiếu + chăn','GiuongXep_CoTam':'Giường xếp (khách)','GoBanCong':'Gờ bê tông ban công','GocKho_DoGio_Fix':'Góc kho: đồ giỗ (nồi đồng, thùng, chiếu)','GocKho_DoNha_Fix':'Góc kho: quạt gãy, chiếu cuộn, mâm nhôm',
'GocKho_DoTet_Fix':'Góc kho: đồ Tết (mai giả, đèn ông sao)','Guitar':'Đàn guitar cũ','GuongTreo_Sanh':'Gương treo sảnh','GuongWC':'Gương WC','HanhLyKhoi_TuiVai':'Hành lý của Khôi (túi vải)','HoaTran':'Hoa trần (phào trang trí)',
'HopBanhQuy_ThiecTaiDung':'Hộp bánh quy thiếc (tái dụng)','HopBut_ThuocKe':'Hộp bút + thước kẻ','HopCongTo':'Hộp công tơ điện','HopKhanGiay_Nhua':'Hộp khăn giấy nhựa','HopKimChi_Me':'Hộp kim chỉ của mẹ','HopThu_Cong':'Hộp thư ở cổng',
'HuBinhNgamRuou':'Hũ / bình ngâm rượu','HuongNen_DuTru':'Hương, nến dự trữ','KeChenTreoTuong':'Kệ chén treo tường','KeGiayDep_Go':'Kệ giày dép gỗ','KeGiay_ChanCau':'Kệ giày chân cầu thang','KeGoDai':'Kệ gỗ dài (kho)',
'KeGo_TreoTuong':'Kệ gỗ treo tường','KeKinh':'Kệ kính','KeKinh_DoBoMe':'Kệ kính đồ dùng (WC bố mẹ)','KeSachHoSo_Go':'Kệ sách hồ sơ gỗ','KeVLo_DoKe':'Kệ sắt V lỗ + đồ kệ','KeXaPhong_WC':'Kệ xà phòng WC','KepPhoi':'Kẹp phơi',
'KetSat_KhoaSo':'Két sắt khoá số','Khan_Ru':'Khăn + móc nhựa (WC)','KhayAmChen':'Khay ấm chén','KhayHoaQua_Nhua':'Khay hoa quả nhựa','KhayTra_LyThuyTinh':'Khay trà ly thuỷ tinh','KhungAnh_CuoiNho':'Khung ảnh cưới nhỏ',
'KhungCuaSatHam':'Khung cửa sắt hầm','KhungCuaWC_BoMe':'Khung cửa WC bố mẹ','KhungCuaWC_T1':'Khung cửa WC tầng 1','KinhLao_HopKinh':'Kính lão + hộp kính','LOC_BanNhoDatMay':'Bàn nhỏ đặt máy điện thoại',
'LOC_BatGao':'Bát gạo (đồ cúng)','LOC_BatMuoi':'Bát muối (đồ cúng)','LOC_CanhQuayHang':'Quầy hàng + ngăn kéo (lọ keo)','LOC_DienThoai_TronBo':'Điện thoại bàn (trọn bộ)','LOC_DongDoCungTang':'Đống đồ cúng đám tang',
'LOC_TapGiay_ButBi':'Tập giấy + bút bi','LanCanSanPhoi':'Lan can sân phơi (mô-đun)','LanCan_BanCong':'Lan can sắt ban công','Lavabo':'Lavabo','LichAm_TreoTuong':'Lịch âm treo tường','LichBloc':'Lịch bloc (5/8)',
'LichBloc_CongTy':'Lịch bloc công ty vật liệu','LichThang8_2002':'Lịch tháng 8/2002','LichTo_2000':'Lịch tờ năm 2000','LoHoaGia_Nhua':'Lọ hoa giả nhựa','Loa_Thung':'Loa thùng','LonSuaDac_DungBut':'Lon sữa đặc đựng bút','LongBan':'Lồng bàn nhựa',
'MacAoDung':'Mắc áo đứng','MamDoCungMan':'Mâm đồ cúng mặn (Đêm 3)','MamDong_HoaQuaTho':'Mâm đồng hoa quả (thờ)','MatBepXay_180':'Mặt bếp xây 1,80 m','MayBom_NuocGiengTroi':'Máy bơm nước (giếng trời)',
'MayTinhBoTui':'Máy tính bỏ túi','MocAo_KhanTam':'Móc áo + khăn tắm','MocChiaKhoa':'Móc chìa khoá (thiếu một chùm)','MocDongPhuc':'Móc treo đồng phục','MuiBac_Mon':'Mũi bậc bo tròn (mòn)','NenSanPhoi':'Nền sân phơi',
'NhatKy_Dong':'Nhật ký (đóng)','NoiChao_Rong':'Nồi cháo','NoiComDien':'Nồi cơm điện','Nokia_DoChuong':'Điện thoại di động đổ chuông','NonLa_TreoTuong':'Nón lá treo tường','OCamKeoDai':'Ổ cắm kéo dài','OCam_Doi':'Ổ cắm đôi',
'OThoang_BongGio':'Ô thoáng bông gió','OngNuocMua_GiengTroi':'Ống nước mưa (giếng trời)','OngNuoc_Bo':'Bó ống nước (kho)','OngNuoc_Nam':'Ống nước nằm (kho)','PhichHoa':'Phích vỏ sắt hoa','Poster_BanNhac':'Poster ban nhạc (bịa)',
'QuanTai_LOC':'Quan tài (LỘC) — đầu về phía bàn thờ','QuatBan_SatCu':'Quạt bàn sắt cũ','QuatCayDung':'Quạt cây đứng','QuatCay_NguyenBo':'Quạt cây (nguyên bộ)','QuatTran_Canh':'Quạt trần — cánh','QuatTran_Than':'Quạt trần — thân',
'QuatTreoTuong_Fix':'Quạt treo tường','RadioCassette_2Loa':'Radio cassette 2 loa','RauQua_Ro':'Rổ rau quả','Rem_Hat':'Rèm hạt nhựa','Rem_Vai_BoMe_Buong':'Rèm vải — phòng bố mẹ','Rem_Vai_Khoi_Buong':'Rèm vải — phòng Khôi',
'Rem_Voan_BoMe':'Rèm voan — phòng bố mẹ','Rem_Voan_Khoi':'Rèm voan — phòng Khôi','Rem_Voan_PhongTho':'Rèm voan trắng — phòng thờ','RoNhua_QuanAoBan':'Rổ nhựa quần áo bẩn','RoRaThit':'Rổ rá + thớt','SM_BurnBasin_Ash':'Chậu đốt vàng mã (tro)',
'SM_BurnBasin_Burning':'Chậu đốt vàng mã (đang cháy)','SM_EnvelopeTray_day':'Khay phong bì phúng viếng','SM_FuneralGate':'Cổng rạp tang','SM_FuneralTent_300':'Rạp tang (khung bạt)','SM_ObituaryBoard':'Bảng cáo phó',
'SM_PlasticChairStack_4':'Chồng 4 ghế nhựa','SM_PlasticChairStack_8':'Chồng 8 ghế nhựa','SM_PlasticChair_Green':'Ghế nhựa xanh','SM_PlasticChair_Red':'Ghế nhựa đỏ','SM_PlasticTable_TableCover':'Bàn nhựa trải khăn (nhận phúng viếng)',
'SachTruyenTranh':'Sách truyện tranh','Salon_BanNuoc':'Bàn nước salon','Salon_Dem_NgoiDai_GanTV':'Đệm ghế dài (gần TV)','Salon_Dem_NgoiDai_Kia':'Đệm ghế dài (phía kia)','Salon_Dem_NgoiDon':'Đệm ghế đơn','Salon_GheDai':'Ghế salon dài',
'Salon_GheDon':'Ghế salon đơn','SapGo':'Sập gỗ thấp','SoHoaDon_Quay':'Sổ hoá đơn trên quầy','SoPhungViengTang':'Sổ phúng viếng','SongSatHoa_Bep':'Song sắt hoa cửa sổ bếp','SongSatHoa_BoMe':'Song sắt hoa cửa sổ bố mẹ',
'SongSatHoa_Khoi':'Song sắt hoa cửa sổ Khôi','TamNilon_PhuBui':'Tấm nilon phủ bụi','ThamChuiChan':'Thảm chùi chân','ThamChuiChan_Cua':'Thảm chùi chân (cửa)','Tham_Chieu_Hoa':'Thảm / chiếu hoa','Tham_Do_1m2':'Thảm đỏ 1,2 m',
'ThangNhom':'Thang nhôm','ThanhRem':'Thanh treo rèm','ThanhSat_Bo':'Bó thanh sắt','ThanhTreoDungCu_Bep':'Thanh treo dụng cụ bếp','Thau_Nhua_QuanAo':'Thau nhựa quần áo','ThungCarton_Chong':'Chồng thùng carton',
'ThungGao_Nhua':'Thùng gạo nhựa','ThungGo':'Thùng gỗ','ThungNuocNgot_Khach':'Thùng nước ngọt phục vụ khách','ThungNuoc_Nap':'Thùng nước có nắp','ThungRac':'Thùng rác','ThungRacNhua':'Thùng rác nhựa + bao đen','ThungSon':'Thùng sơn',
'ThungSon_Cum2':'Cụm thùng sơn','ThuocBo_LoThuocNam':'Lọ thuốc nam của bố','TranGiatCap_Khung':'Trần thạch cao giật cấp','TranhHoaSen_Khung':'Tranh hoa sen (khung)','TranhNho_HanhLang':'Tranh nhỏ hành lang','TranhSap_Nhim':'Tranh sáp màu "cả nhà" của Nhím',
'TranhSonThuy_Khung':'Tranh sơn thuỷ (khung)','TranhTheu_Tex':'Tranh thêu thuyền buồm','TranhThuPhap_Phuc':'Tranh chữ "Phúc" (quốc ngữ)','TruDauThang':'Trụ đầu thang gỗ tiện','TuAo_Khoi':'Tủ áo của Khôi','TuBuffet_ChenBat':'Tủ chạn chén bát',
'TuDauGiuong':'Tủ đầu giường','TuDoTho_Fix':'Tủ đồ thờ','TuDung_RuongChanMan':'Tủ đứng (rương chăn màn)','TuHoSo_Sat':'Tủ hồ sơ sắt','TuKinh':'Tủ kính 3 tầng (tiệm)','TuLanh_Bo':'Tủ lạnh một cánh','TuNhua_Nhim':'Tủ nhựa ghép của Nhím',
'TuQuanAo_GamHo':'Tủ quần áo gầm hở (két sắt dưới gầm)','TuTV_Dung_Bo':'Tủ TV đứng + TV, VCD, loa','TuThap_Sanh':'Tủ thấp sảnh','TuiGiaVi_Treo':'Túi gia vị treo','TuiNilon_Treo':'Túi nilon treo','TuiXachMe_ViTien':'Túi xách của mẹ (ví)',
'TuongBuaMau':'Tường dán kín bùa (hầm)','VaiChePhuGuong_Sanh':'Vải che gương — sảnh','VaiChePhuGuong_WC':'Vải che gương — WC','VoiSen':'Vòi sen','VongHoa_Heo':'Vòng hoa (héo)','VongHoa_Tuoi':'Vòng hoa (tươi)',
'Walkman_BangCu':'Máy nghe băng + băng cũ','XeDap_Khoi':'Xe đạp cũ của Khôi','XeRua':'Xe rùa','XiBet_Tron':'Xí bệt','XoChauKhanLau':'Xô chậu khăn lau','XoGao_Up':'Xô gáo úp',
'VaiPhuQuanTai_A':'Vải phủ quan tài A','VaiPhuQuanTai_B':'Vải phủ quan tài B',
}
def vi(name):
    if name in VI: return VI[name]
    base=name.split(' (')[0]
    if base in VI: return VI[base]
    return name
